### ISSUE TITLE
[API] 通知機能の実装

### ISSUE THREAD

**Issue by kyontan** [kyontan/ictsc-score-server#3]

**Comment by whywaita** [comment]
:+1:

**Comment by kyontan** [comment]
Notification モデルを新しく作って、コメントの作成/編集等があったらそこへどんどん突っ込んでいけばいいかなと思っています。

**Comment by kyontan** [comment]
プッシュ通知については一先ず後回しでよくて、ポーリング(コメット) での実装を行えばよいかなと思います。

**Comment by kyontan** [comment]
権限周り考えるのが難しい。
現行の Permission モデルと組み合わせると query が複雑になりそう

**Comment by kyontan** [comment]
通知について考えた

`GET /notifications`
通知全件

`GET /notifications/unread`
そのメンバーがまだ既読にしていない通知全て

`POST /notifications/mark_as_read`
パラメータで指定した時刻までの通知を既読にする

```{
    id: 12345
    type: "new_comment_to_problem",
    text: "問題へ補足が追加されました",
    resouce: "Problem",
    resouce_id: "2",
    sub_resource: "Comment",
    sub_resource_id: 5,
    created_at: ...
}```

**Comment by kyontan** [comment]
これ、resource や sub_resource というのを Notification がもつ必要はないですね。
(該当するリソースが削除されたら、それに関連する Notification も消えるべきなので)

Nofitication が持つべきなのは、

```
id: integer
type: string
notificatable_type: string
notificatable_id: integer
created_at: datetime
updated_at: datetime
```

だと思う

**Comment by kyontan** [comment]
ICTSC6 でやってた

**Comment by kyontan** [comment]
Ref: ce088ca897daa24d874785d35d38d258fb395e1e
