### ISSUE TITLE
得点のグラフ表示

### ISSUE THREAD

**Issue by h-otter** [kyontan/ictsc-score-server#31]
http://www.atmarkit.co.jp/fsecurity/special/167ctf/zu01l.jpg

こういうのあったらいいですね 🙏

**Comment by kyontan** [comment]
/api/scores にファーストブラッド等の情報を含むようになったので、API側としては対応可能です。
フロントエンド側の実装をすれば実現できます。

(refs: #32, #33)

**Comment by kyontan** [comment]
Finally developed! https://github.com/kyontan/ictsc-score-server/commit/b4e6b78998046f1253d1a14011a3a84bb72100a7
