### ISSUE TITLE
answer.completed_atを実装する

### ISSUE THREAD

**Issue by kamijin-fanta** [kyontan/ictsc-score-server#49]
`answer.updated_at + contest.answer_reply_delay_sec` が解答の開示時刻

**Comment by kyontan** [comment]
`answer.completed_at` + `contest. answer_reply_delay_sec` が解答の開示時刻になりました

https://github.com/kyontan/ictsc-score-server/commit/a083ce1dd189a4d70b5694d765ba1e95ead54bc0
