### ISSUE TITLE
通知アイテムの修正

### ISSUE THREAD

**Issue by kyontan** [kyontan/ictsc-score-server#59]
/api/notifications を ICTSC7 仕様に修正する

**Comment by kyontan** [comment]
- type: `competition_started`
    - text: 競技が開始しました
- type: `problem_opened`
    - text: 新たな問題が解放されました
- type: `issue_replied`
    - text: 質問への返答がありました
- type: `score_opened`
    - text: 問題の採点結果が公開されました
- type: `competition_finished`
    - text: 競技が終了しました

 ```ruby
{
  resource: "Comment",
  resource_id: 57,
  sub_resource: "Issue",
  sub_resource_id: 10,
  type: "created_comment_to_issue",
  text: "問題への質問が投稿されました。",
  created_at: "2017-03-01T17:05:11.000+09:00"
}
```

**Comment by kyontan** [comment]
Implemented in: https://github.com/kyontan/ictsc-score-server/commit/faaf70c5238d164d66578a9cf1804611e7ab0af3 https://github.com/kyontan/ictsc-score-server/commit/1fd557729c97729b8428eadd89d488b9654f65b0

**Comment by whywaita** [comment]
Good!

**Comment by suzutan** [comment]
:+1:
